delegateas/XrmMockup

src/XrmMockupShared/Core.cs
=> Removed excessive console output.

src/XrmMockup365/XrmMockup365.csproj, src/XrmMockupShared/Core.cs, src/XrmMockupShared/Requests/IsValidStateTransitionRequestHandler.cs, src/XrmMockupShared/Requests/RetrieveExchangeRateRequestHandler.cs, src/XrmMockupShared/XrmMockupShared.projitems, tests/SharedTests/TestCurrency.cs, tests/SharedTests/TestStates.cs
Added support for IsValidStateTransitionRequest and RetreiveExchangeRateRequest
=> 28 add support for is valid state transition request and retrieve exchange rate request

Tools/Daxif/_Config.fsx, src/XrmMockupShared/Core.cs, src/XrmMockupShared/Requests/CloseIncidentRequestHandler.cs, src/XrmMockupShared/Requests/IsValidStateTransitionRequestHandler.cs, src/XrmMockupShared/Utility.cs, src/XrmMockupShared/XrmMockupShared.projitems, tests/SharedTests/SharedTests.projitems, tests/SharedTests/TestIncident.cs, tests/SharedTests/UnitTestBase.cs, tests/TestPluginAssembly11/Context/XrmContext.cs, tests/TestPluginAssembly13/Context/XrmContext.cs, tests/TestPluginAssembly15/Context/XrmContext.cs, tests/TestPluginAssembly16/Context/XrmContext.cs, tests/TestPluginAssembly365/Context/XrmContext.cs
=> 32 implement close incident

src/XrmMockupShared/Requests/RetrieveMultipleRequestHandler.cs, tests/SharedTests/TestRetrieveMultiple.cs
=> Total record count

src/MetadataShared/DataHelper.cs, src/MetadataShared/Program.cs
Metadatagenerator365 now only gets workflows from the active solution
=> Workflow metadatagen

src/XrmMockupShared/Workflow/WorkflowManager.cs
allow workflows to be created as instances of abstract classes
=> cope with workflows being instances of abstract classes

src/XrmMockupShared/TracingService.cs, tests/SharedTests/SharedTests.projitems, tests/SharedTests/TestTracingService.cs
=> 133 xml format trace message

src/XrmMockupShared/Core.cs, src/XrmMockupShared/Requests/RetrieveMultipleRequestHandler.cs, src/XrmMockupShared/Requests/RetrieveRequestHandler.cs, tests/SharedTests/TestMoney.cs
=> 139 calc fields retrieve multiple

src/XrmMockupShared/Core.cs, tests/SharedTests/SharedTests.projitems, tests/SharedTests/TestRetrieve.cs, tests/SharedTests/TestRetrieveNoProxyTypes.cs, tests/SharedTests/UnitTestBase.cs, tests/SharedTests/UnitTestBaseNoProxyTypes.cs, tests/SharedTests/XrmmockupCollectionNoProxyTypes.cs, tests/SharedTests/XrmmockupFixtureNoProxyTypes.cs
=> 140 formatted values lookup names

src/XrmMockupShared/Core.cs, src/XrmMockupShared/XrmMockupShared.projitems, tests/SharedTests/TestMetadata.cs
=> 135 metatdata changes

src/XrmMockupShared/Security.cs
=> don't cascade ownership changes to business owned entities

src/XrmMockupShared/Requests/AssociateRequestHandler.cs, src/XrmMockupShared/Requests/CreateRequestHandler.cs, src/XrmMockupShared/Requests/UpdateRequestHandler.cs
=> throw more dynamics style exceptions

src/XrmMockupShared/Database/XrmDb.cs
=> dont rely on exception to not find row

src/XrmMockupWorkflow/WorkflowConstructor.cs
=> variables of type scg:Dictionary(x:String, x:Object)

src/XrmMockupShared/Utility.cs, tests/SharedTests/SharedTests.projitems, tests/SharedTests/TestClone.cs
=> clone object properties properly

src/XrmMockupShared/Utility.cs, tests/SharedTests/TestRetrieve.cs
=> trim full name correctly

src/MetadataShared/Program.cs
=> Added logging of when the metadata has been generated.

src/XrmMockup2011/XrmMockup.cs, src/XrmMockupShared/Core.cs, src/XrmMockupShared/Requests/RetrieveCurrentOrganizationRequestHandler.cs, src/XrmMockupShared/XrmMockupSettings.cs, src/XrmMockupShared/XrmMockupShared.projitems
Implements feature request #217 adding RetrieveCurrentOrganizationHandler and making it configurable with XrmMockupSettings
=> 217 add retrieve current organization request

src/XrmMockupShared/Core.cs
https://github.com/thygesteffensen/PAMU_CDS is depending on XrmMockup and has written its own version of MockupService during its infancy. This is not needed. Tested in my local project using PAMU CDS
=> Use MockupService instead of XrmExtension

RELEASE_NOTES.md, src/XrmMockupShared/Requests/RetrieveMultipleRequestHandler.cs, tests/SharedTests/TestOrderByQueryExpression.cs
Allow multiple thenby orderings in retrievemultiple
=> Support multiple thenby

src/XrmMockupWorkflow/WorkflowTree.cs, tests/SharedPluginsAndCodeactivites/AccountWorkflowActivity.cs
=> Set InitiatingUserId and UserId in workflow context

src/XrmMockupShared/Core.cs, src/XrmMockupShared/Plugin/CustomApiManager.cs, src/XrmMockupShared/XrmMockupSettings.cs, src/XrmMockupShared/XrmMockupShared.projitems, tests/SharedPluginsAndCodeactivites/CreateAccountApi.cs, tests/SharedPluginsAndCodeactivites/CustomAPI.cs, tests/SharedPluginsAndCodeactivites/SharedPluginsAndCodeactivites.projitems, tests/SharedTests/SharedTests.projitems, tests/SharedTests/TestCustomApi.cs, tests/SharedTests/XrmmockupFixture.cs
- Added a new `CustomApiManager` class to manage custom APIs in the `Core` class.
- Updated the `Core` class to include an instance of `CustomApiManager`.
- Modified the `Execute` method in the `Core` class to pass an additional `pluginContext` parameter to the `ExecuteRequest` method.
- Updated the `ExecuteRequest` method to handle custom API requests by checking if the `CustomApiManager` can handle the request and executing it if so.
- Added a new `BaseCustomApiTypes` property to the `XrmMockupSettings` class to store the base types of custom APIs.
- Included the new `CustomApiManager.cs` file in the project files.
- Added new custom API classes `CreateAccountApi` and `CustomAPI` to handle custom API logic.
- Added a new test class `TestCustomApi` to test the custom API functionality.
- …
=> Add CustomApiManager and custom API handling

src/XrmMockupShared/Core.cs, src/XrmMockupShared/Requests/ExecuteTransactionRequestHandler.cs, src/XrmMockupShared/XrmMockupShared.projitems, tests/SharedTests/SharedTests.projitems, tests/SharedTests/TestExecuteTransaction.cs
- Updated `InitializeDB` in `Core.cs` to include `ExecuteTransactionRequestHandler`.
- Added compilation entry for `ExecuteTransactionRequestHandler.cs` in `XrmMockupShared.projitems`.
- Included new test file `TestExecuteTransaction.cs` in `SharedTests.projitems`.
- Implemented logic for handling transaction requests in `ExecuteTransactionRequestHandler.cs`.
- Created unit tests for successful and failed transaction scenarios in `TestExecuteTransaction.cs`.
=> Add ExecuteTransactionRequestHandler and related tests

src/XrmMockupShared/Utility.cs
Added `regardingobjectid` to `ToActivityPointer` for context. Rest is VS Cleanup.
Next step is to make Utility.Activites and Utility.ActivityCodes dynamic.
=> Added `regardingobjectid` to `ToActivityPointer` for context.
