delegateas/XrmMockup

src/MetadataShared/DataHelper.cs
In some cases, the objecttypecode "none" will be returned multiple times, with the same state <-> status mapping, resulting in a DuplicateKey exception.
=> Add guard before attempting to add a state <-> status mapping from statusmap.

src/MetadataShared/DataHelper.cs
Is it too much to check if the entities contains the expected attributes?
If not, should we also check if the Attributes' value is null?
=> Added comprehensive null check in Datahelper.cs GetSecurityRoles

src/XrmMockupShared/Utility.cs
For some linq expressions like:
```
var woQuery = from brb in ctx.BookableResourceBookingSet
join wo in ctx.msdyn_workorderSet on brb.msdyn_WorkOrder.Id equals wo.Id
where wo.msdyn_ServiceAccount.Id == accRef.Id
select brb;
```
ConvertToComparableObject will sometimes return a wrong type.
In this case `EvaluateCondition` is detecting attr as an `AliasValue` and then return the value. In this case the value will be an EntityReference and not a `Guid`. 
To account for this and other cases, it is necessary to recersively call ConvertToComparableObject for AliasValues.
=> Recersive call to ConvertToComparableObject for AliasedValue

src/XrmMockupShared/Database/DbRow.cs, src/XrmMockupShared/Database/XrmDb.cs, src/XrmMockupShared/Requests/RetrieveMultipleRequestHandler.cs, src/XrmMockupShared/Utility.cs, tests/SharedTests/TestRetrieveMultiple.cs
Fixes #174 
Added a sequence field to each row added (thread-safe) to allow RetrieveMultiple to return rows in the order created (Dynamics default behaviour if no sort order specified)
Parallelized and consolidated a number of the loops inside RetrieveMultipleRequestHandler.
These changes give no discernible improvements on XrmMockup's own test suite, but give something like a 30% increase on my own real world tests (29mins ->20mins)
=> parallel performance improvements

src/MetadataShared/DataHelper.cs
The security role ServiceReader contains the same access right twice after what I assume is a faulty update by Microsoft. This change handles this error in the CRM data.
=> Handle duplicate access right for same security role

src/MetadataShared/DataHelper.cs
In order to match the later retrieved entity images the id is required. so far it was always guid.empty. So I added the id to the query expression.
=> Add sdkmessageprocessingstepid to pluginQuery.

src/XrmMockupWorkflow/ParseStructure.cs, src/XrmMockupWorkflow/WorkflowConstructor.cs, src/XrmMockupWorkflow/WorkflowTree.cs
Respect TargetType when assigning final value to entity.
Do not translate type when reading from entity.
The TargetType property is propagated from the end-target to any input values.
This was used to cast the input values, but that would result in the types being wrong during computation.
Instead, cast to the target type before writing the value in `SetEntityProperty`.
This was observed in new `caseage` calculated field added as part of release wave 2
=> Add TargetType to SetEntityProperty actions.

appveyor.yml, src/XrmMockup365/XrmMockup365.csproj, src/XrmMockupShared/Database/OrganizationHelper.cs, src/XrmMockupShared/MockupService.cs, src/XrmMockupShared/MockupServiceAsync.cs, src/XrmMockupShared/MockupServiceProviderAndFactory.cs, src/XrmMockupShared/XrmMockupBase.cs, src/XrmMockupShared/XrmMockupBaseAsync.cs, src/XrmMockupShared/XrmMockupShared.projitems, src/XrmMockupWorkflow/IWorkflowContext.cs, src/XrmMockupWorkflow/XrmMockupWorkflow.projitems, src/XrmMockupWorkflow/XrmTimeSpan.cs
Add .NET6 target to  XrmMockup365 project.
Add compile-time constant and include Dataverse Service Client if compiling for .NET6
Implement IOrganizationServiceAsync, included in Dataverse Service Client
This fixes #189
=> Add support for .NET6 by multi-targeting XrmMockup365

src/XrmMockupShared/XrmMockupBase.cs
I tried using XrmMockup in .NET 6 with the new update. It almost worked.
For some reason XrmMockup saw the path to the same assembly multiple times. Which caused it to load the same DLL multiple times.
This is possible because we use the method `Assembly.LoadFile` instead of `Assembly.LoadFrom`. This SO post lead me down that road to fix it https://stackoverflow.com/questions/56146804/assembly-loading-happens-twice
I changed that method, tested XrmMockup365 locally, and it works in my project now as well as all the tests in XrmMockup.
=> Fixed error where the same DLL could be loaded multiple times

RELEASE_NOTES.md, src/MetadataGen/MetadataGenerator11/AssemblyInfo.fs, src/MetadataGen/MetadataGenerator13/AssemblyInfo.fs, src/MetadataGen/MetadataGenerator15/AssemblyInfo.fs, src/MetadataGen/MetadataGenerator16/AssemblyInfo.fs, src/MetadataGen/MetadataGenerator365/AssemblyInfo.fs, src/XrmMockup2011/AssemblyInfo.fs, src/XrmMockup2011/XrmMockup.cs, src/XrmMockup2013/AssemblyInfo.fs, src/XrmMockup2013/XrmMockup.cs, src/XrmMockup2015/AssemblyInfo.fs, src/XrmMockup2015/XrmMockup.cs, src/XrmMockup2016/AssemblyInfo.fs, src/XrmMockup2016/XrmMockup.cs, src/XrmMockup365/AssemblyInfo.fs, src/XrmMockup365/XrmMockup.cs, src/XrmMockupShared/Core.cs, src/XrmMockupShared/MockupServiceProviderAndFactory.cs, src/XrmMockupShared/Plugin/PluginManager.cs, src/XrmMockupShared/Requests/CalculateRollupFieldRequestHandler.cs, src/XrmMockupShared/Requests/DeleteRequestHandler.cs, src/XrmMockupShared/Requests/RetrieveMultipleRequestHandler.cs, src/XrmMockupShared/TracingService.cs, src/XrmMockupShared/TracingServiceFactory.cs, src/XrmMockupShared/Workflow/WorkflowManager.cs, src/XrmMockupShared/XrmMockupBase.cs, src/XrmMockupShared/XrmMockupSettings.cs, src/XrmMockupShared/XrmMockupShared.projitems, tests/SharedTests/TestTracingService.cs, tests/SharedTests/TestZipSnapshot.cs
Add functionality to instantiate a new XrmMockup instance based on an existing one.
This allows us to run multiple instances in parallel, withou having to fully load XrmMockup each time, significantly speeding up the initialization time and reducing file IO.
=> Instantiate new instance based on existing metadata

src/XrmMockupShared/Core.cs, src/XrmMockupShared/Mappings.cs, src/XrmMockupShared/Requests/RetrieveMultipleRequestHandler.cs, tests/SharedPluginsAndCodeactivites/RetrievePlugin.cs, tests/SharedPluginsAndCodeactivites/SharedPluginsAndCodeactivites.projitems, tests/SharedTests/TestRetrieve.cs, tests/SharedTests/TestRetrieveMultiple.cs
Fixes #227 
Add support for Retrieve plugins
Fixes #230 
Extend RetrieveMultipleRequestHandler to support `Distinct` specifications in `QueryExpressions`
Closes #203 
Add a unit test to research this issue. It seems to be solved. At least the RetrieveMultiple request throws an AggregateException, because the attribute failure happens within a Parallel.forEach loop.
=> Retrieve and RetrieveMultiple fixes

src/XrmMockupShared/Requests/CloseIncidentRequestHandler.cs, src/XrmMockupShared/Requests/UpdateRequestHandler.cs, tests/SharedPluginsAndCodeactivites/IncidentDeleteAllRelatedResolutionsOnClose.cs, tests/SharedPluginsAndCodeactivites/SharedPluginsAndCodeactivites.projitems, tests/SharedTests/TestIncident.cs
Fixes #208 
In `CloseIncidentRequestHandler` use `UpdateRequest` instead of `SetStateRequest`
Fixes #93 
In `UpdateRequestHandler` check if the target entity is an Incident whose state is Resolved. If yes, throw a FaultException.
Introduce custom parameter `CloseIncidentRequestHandler` to detect if the call was made from that particular handler. If yes, then ignore the check and update the incident as resolved.
=> Resolve incident fixes

src/XrmMockupShared/Core.cs, src/XrmMockupShared/Database/DbAttributeTypeMap.cs, src/XrmMockupShared/Requests/SendEmailRequestHandler.cs, src/XrmMockupShared/XrmMockupShared.projitems, tests/SharedTests/SharedTests.projitems, tests/SharedTests/TestSendEmail.cs
Fixes #75 
Implemented SendEmailRequestHandler. However, implementing handler for SendEmailFromTemplate has proven to quite a bit more complicated, because the current context and metadata is based on a deprecated environment.
Fixes #96 
Changed mapping of `PartyList `from `DbRow[]` to `EntityCollection`. This made it possible to validate the `from` and `to` fields in the new request handler.
=> Implemented SendEmailRequestHandler

src/MetadataShared/DataHelper.cs, src/XrmMockupShared/Core.cs, src/XrmMockupShared/Requests/CommitFileBlocksUploadRequestHandler.cs, src/XrmMockupShared/Requests/InitializeFileBlocksUploadRequestHandler.cs, src/XrmMockupShared/Requests/UploadBlockRequestHandler.cs, src/XrmMockupShared/XrmMockupShared.projitems
Adds boilerplate support for the three requiests
"InitializeFileBlocksUpload",
"UploadBlockRequest",
"CommitFileBlocksUploadRequest"
No file store implemented, but works for barebone testing in current customer.
Tested locally.
=> Add file block upload handlers

RELEASE_NOTES.md, src/MetadataGen/MetadataGenerator365/AssemblyInfo.fs, src/XrmMockup365/AssemblyInfo.fs, src/XrmMockup365/XrmMockup365.csproj, src/XrmMockupShared/Requests/UpdateRequestHandler.cs, tests/SharedTests/TestIncident.cs
An error was introduced when state is not part of an incident update request.
Check that the parameter is set before trying to access it.
=> FIX: Avoid NullReferenceException in incident update handler

src/XrmMockupShared/Core.cs, src/XrmMockupShared/Requests/InstantiateTemplateRequestHandler.cs, src/XrmMockupShared/XrmMockupShared.projitems, tests/SharedTests/SharedTests.projitems, tests/SharedTests/TestInstantiateTemplate.cs, tests/SharedTests/TestSendEmail.cs
Reorganized and updated `using` directives in `Core.cs` for better code organization. Added `InstantiateTemplateRequestHandler` to `InitializeDB` method in `Core.cs` to handle `InstantiateTemplate` requests. 
Updated `XrmMockupShared.projitems` to include `InstantiateTemplateRequestHandler.cs`.
Added new file `InstantiateTemplateRequestHandler.cs` defining the `InstantiateTemplateRequestHandler` class, which handles `InstantiateTemplate` requests by creating an `email` entity and returning it in an `EntityCollection` within the `InstantiateTemplateResponse`. Added validation checks in `Execute` method for `TemplateId`, `ObjectId`, and `ObjectType`. Throws `FaultException` if any validation fails.
Added tests for `InstantiateTemplateRequest` validation and response.
=> Implemented InstantiateTemplateRequest

src/XrmMockupShared/Requests/RetrieveMultipleRequestHandler.cs, tests/SharedTests/TestRetrieveMultiple.cs
- Add support for TopCount and Take clauses in retrieve multiple requests.
- Refactor handler to limit EntityCollection initializations
- Verify that Skip is supported with unit test
=> Extend RetrieveMultipleRequestHandler

src/XrmMockupShared/Core.cs, src/XrmMockupShared/Plugin/PluginManager.cs, tests/SharedPluginsAndCodeactivites/SharedPluginsAndCodeactivites.projitems, tests/SharedPluginsAndCodeactivites/SyncAsyncTest/Test1/Test1Plugin1.cs, tests/SharedPluginsAndCodeactivites/SyncAsyncTest/TestPlugin0.cs, tests/SharedTests/SharedTests.projitems, tests/SharedTests/TestExecutionOrder.cs, tests/SharedTests/TestSyncAsyncPlugin.cs
Fixes #94 
- Rewrite PluginManager to collect synchronous trigger functionality within one function
- Use new function to execute plugins with execution order zero first. Then real-time workflows. Then remaining synchronous plugins.
- Update postImage after synchronous logic have executed and save it in a new dedicated variable
- Align 'StageAsync' with rewritten function 'TriggerSync'
- Test using existing plugins and workflows as well as one new plugin with execution order zero
=> Fix plugin vs workflow execution order

src/MetadataGen/MetadataGenerator365/AssemblyInfo.fs, src/XrmMockup365/AssemblyInfo.fs, src/XrmMockup365/XrmMockup365.csproj, src/XrmMockupShared/Core.cs, src/XrmMockupShared/Database/XrmDb.cs, src/XrmMockupShared/Domain.cs, src/XrmMockupShared/Mappings.cs, src/XrmMockupShared/Plugin/PluginContext.cs, src/XrmMockupShared/Plugin/PluginManager.cs, src/XrmMockupShared/Requests/CreateMultipleRequestHandler.cs, src/XrmMockupShared/Requests/UpdateMultipleRequestHandler.cs, src/XrmMockupShared/Requests/UpsertMultipleRequestHandler.cs, src/XrmMockupShared/Requests/UpsertRequestHandler.cs, src/XrmMockupShared/Workflow/WorkflowManager.cs, src/XrmMockupShared/XrmMockupShared.projitems, tests/SharedPluginsAndCodeactivites/Plugin.cs, tests/SharedPluginsAndCodeactivites/SetCityOnCreateUpdateMultiple.cs, tests/SharedPluginsAndCodeactivites/SetCountryOnCreateUpdate.cs, tests/SharedPluginsAndCodeactivites/SharedPluginsAndCodeactivites.projitems, tests/XrmMockup365Test/TestUpdateMultipleRequestHandler.cs, tests/XrmMockup365Test/TestUpdateMultipleRequestPlugin.cs, tests/XrmMockup365Test/TestUpsertMultiple.cs
This pull request includes several changes to add new request handlers, and improve the codebase by refining existing logic and adding new mappings. The most important changes include adding new request handlers, and refining logic for event operations.
* [`src/XrmMockupShared/Core.cs`](diffhunk://#diff-292f698c02eeed504ced46ef567bc0d2588d52523bbb5d73bb44ca70cad03760R218-R219): Added `UpdateMultipleRequestHandler` and `UpsertMultipleRequestHandler` in the `InitializeDB` method.
* [`src/XrmMockupShared/Core.cs`](diffhunk://#diff-292f698c02eeed504ced46ef567bc0d2588d52523bbb5d73bb44ca70cad03760L593-R595): Refined logic in the `Execute` method to use `EventOperation` type and added checks for `shouldTrigger` and `eventOp` being `EventOperation`. …
=> Add support for UpdateMultiple and UpsertMultiple requests

src/MetadataShared/AssemblyGetter.cs
Updates the `AssemblyGetter.GetAssemblyFromName`  and ` AssemblyGetter.GetAssembiesInBuildPath` methods to improve compatibility with SDK-style .csproj files.
=> Fix assembly lookup to support SDK-Style .csproj files

src/XrmMockupShared/Utility.cs, tests/SharedTests/TestRetrieveMultiple.cs
Updated MatchesCriteria in Utility.cs to handle cases where condition.CompareColumns is true, checking if specified columns exist and comparing their values. Added TestColumnComparison in TestRetrieveMultiple.cs to verify this functionality.
=> Add column comparison in MatchesCriteria and new test

src/XrmMockupShared/Requests/RetrieveMultipleRequestHandler.cs, src/XrmMockupShared/Requests/RetrieveRequestHandler.cs, src/XrmMockupShared/Utility.cs
If the value was invalid (e.g. a stray 0 instead of an existing value), it would throw an opaque NullReferenceException from inside mockup, which could be hard to track down.
Now throws an exception detailing which value is wrong and where.
=> Throw better exception when attempting to format an invalid OptionSet value

src/XrmMockupShared/Requests/RetrieveMultipleRequestHandler.cs, tests/SharedTests/TestRetrieveMultiple.cs
Fix: When not returning the attributes that are being used for ordering, they get evaluated AFTER they have been removed, thus ruining the ordering
=> Fix ordering regression

src/XrmMockup365/XrmMockup365.csproj, src/XrmMockupShared/Core.cs, src/XrmMockupShared/Domain.cs, src/XrmMockupShared/FormulaFieldEvaluator.cs, src/XrmMockupShared/Requests/CalculateRollupFieldRequestHandler.cs, src/XrmMockupShared/Requests/RetrieveAllEntitiesRequestHandler.cs, src/XrmMockupShared/Requests/RetrieveEntityRequestHandler.cs, src/XrmMockupShared/Requests/RetrieveMultipleRequestHandler.cs, src/XrmMockupShared/Requests/RetrieveRequestHandler.cs, src/XrmMockupShared/Utility.cs, src/XrmMockupShared/XrmMockupShared.projitems, tests/SharedTests/TestRetrieve.cs, tests/SharedTests/TestRetrieveMultiple.cs, tests/SharedTests/UnitTestBase.cs, tests/SharedTests/XrmmockupFixture.cs, tests/TestPluginAssembly365/Context/XrmContext.cs, tests/XrmMockup365Test/TestFormulaFields.cs
If a PowerFx field is included in a Retrieve or RetrieveMultiple call it will be evaluated.
Built based on the published packages from Microsoft. These are only published as pre-release currently.
Does not support using a PowerFx field for filtering.
=> Added support for evaluating PowerFx backed Formula fields

src/XrmMockupShared/Core.cs, src/XrmMockupShared/Workflow/WorkflowManager.cs
Currently pending workflows are just hanging after a reset if they are all included. This will cause errors once the waiting workflow executes and tries to fetch records that no longer exist
=> Clear waiting workflows on reset when all workflows included

src/XrmMockupShared/Core.cs, src/XrmMockupShared/Requests/UpdateRequestHandler.cs, tests/SharedTests/TestCreate.cs, tests/SharedTests/TestUpdate.cs
The Microsoft.Xrm.Sdk supports setting the 1-M and M-M relationships properties directly.
For a create request the SDK even creates the related entities if they do not exists (this was already implemented prior to this PR in XrmMockup, however was not included in the stronglytypedentity creation). Creating related entities this way, even has some performance benefits (if interested read: https://temmyraharjo.wordpress.com/2024/03/03/dataverse-performance-benchmark-create-related-entity-via-chain-of-create-vs-relatedentities-property/)
For update i found the SDK to throw an error instead of creating the entities, hence the difference in Create- and UpdateRequestHandler implementations.
✅ Added cloning of RelatedEntities in stronglytypedentity creation
✅ Added association logic similar to …
=> Support for creation and update with IEnumerable relation properties

src/XrmMockupShared/Core.cs, src/XrmMockupShared/XrmMockupSettings.cs, tests/XrmMockup365Test/TestFormulaFields.cs
- Updated `ExecuteCalculatedFields` to check `EnablePowerFxFields` setting.
- Introduced `EnablePowerFxFields` property in `XrmMockupSettings` with default value `true`.
- Added `CanEvaluateExpressionWithUtcToday` test in `TestFormulaFields` for `UTCToday()` evaluation.
=> Add PowerFx field evaluation settings and tests

src/XrmMockup365/Utility.cs, src/XrmMockup365/XmlHandling.cs, tests/XrmMockup365Test/TestRetrieveMultiple.cs
Refactored the `ConvertTo` method in `Utility.cs` to improve type conversion logic, add null checks, and support additional scenarios like string-to-boolean conversion. Updated the `Matches` method to use the refactored `ConvertTo` for consistent type handling.
Added tests for query and fetch expressions with `Guid` and `statecode` filters.
=> Improve type handling in CovertTo, and the In and Not-In operators for query and fetch expressions
